import aka from '../img/koi-list/aka.jpg'

export const Listkoi = [
    {
       koiID: '1',
       name: 'Aka-matsuba',
       Image: aka,
       Length: '15 cm to over 75 cm',
       Weight: '0,1 kg to over 10kg',
       Breed: 'Purebred Japanese Koi',
       Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
    },
    {
        koiID: '2',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '3',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '4',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '5',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '6',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '7',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '8',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '9',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '10',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '11',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '12',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '13',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '14',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '15',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '16',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '17',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },
     {
        koiID: '18',
        name: 'Aka-matsuba',
        Image: aka,
        Length: '15 cm to over 75 cm',
        Weight: '0,1 kg to over 10kg',
        Breed: 'Purebred Japanese Koi',
        Describe: 'Aka Koi has bright red color, slender body, gentle temperament, and can reach large sizes when fully grown.',
     },

]